#!/usr/bin/env python3
"""Regenerate the applied-lessons index from anchor comments.

Truth flows one way: anchors in the instruction files and compressed
Applied entries in the queue are the sources; INDEX.md is derived. Never
edit the index by hand — rerun this script.

Usage:
    python3 .agents/skills/improving-harness-metalearn/scripts/regen_index.py \
        [--root DIR] [--queue FILE] [--out FILE] [--check]

Paths default to the standard locations and resolve against --root, so
the script works from any working directory. `--check` writes
nothing and exits 1 when the on-disk index is absent or differs from the
regenerated one.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ANCHOR_RE = re.compile(r"^<!-- lesson: ([a-z0-9]+(?:-[a-z0-9]+)*) -->$")
ENTRY_RE = re.compile(r"^### ([a-z0-9-]+) \((\d{4}-\d{2}-\d{2})\)$")


def _iter_instruction_files(root: Path):
    for pattern in ("skills/**/*.md", "agents/*.md", "AGENTS.md", ".agents/skills/**/SKILL.md", ".agents/skills/**/procedures/*.md"):
        yield from sorted(root.glob(pattern))


def collect_anchors(root: Path) -> dict[str, list[str]]:
    """Map each anchor slug to the files carrying it, ignoring fenced blocks."""
    anchors: dict[str, list[str]] = {}
    for path in _iter_instruction_files(root):
        in_fence = False
        for line in path.read_text().splitlines():
            stripped = line.lstrip()
            if stripped.startswith("```") or stripped.startswith("~~~"):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            match = ANCHOR_RE.match(line.strip())
            if match:
                anchors.setdefault(match.group(1), []).append(
                    str(path.relative_to(root))
                )
    return anchors


def parse_applied(queue: Path) -> tuple[dict[str, tuple[str, str]], list[str]]:
    """Read compressed Applied entries: `### <slug> (<date>)` plus one body line."""
    applied: dict[str, tuple[str, str]] = {}
    malformed: list[str] = []
    in_applied = False
    last_slug: str | None = None
    for line in queue.read_text().splitlines():
        if line.startswith("## "):
            in_applied = line == "## Applied"
            continue
        if not in_applied:
            continue
        match = ENTRY_RE.match(line)
        if match:
            last_slug = match.group(1)
            applied[last_slug] = (match.group(2), "")
            continue
        if line.strip() and last_slug is not None:
            date, first = applied[last_slug]
            if not first:
                applied[last_slug] = (date, line.strip())
            elif last_slug not in malformed:
                malformed.append(last_slug)
    return applied, malformed


def build_index(applied: dict[str, tuple[str, str]], anchors: dict[str, list[str]]):
    lines = [
        "# Applied-lessons index",
        "",
        "Generated by `scripts/regen_index.py` — do not edit by hand; regenerate.",
        "Unanchored lessons are printed to stdout on generation, not silently kept.",
        "",
        "| slug | applied | targets | anchors | what landed |",
        "|---|---|---|---|---|",
    ]
    unanchored = []
    for slug, (date, one_liner) in sorted(applied.items()):
        base = slug.rsplit("-", 1)[0] if slug[-1].isdigit() else slug
        # multi-hunk slugs (slug-2) count toward the base lesson's anchor total
        # and their files count toward its targets
        hunks = [p for s, ps in anchors.items() if s == slug or
                 (s.startswith(base + "-") and s[len(base) + 1:].isdigit())
                 for p in ps]
        if not hunks:
            unanchored.append(slug)
            continue
        lines.append(
            f"| {slug} | {date} | {', '.join(dict.fromkeys(hunks))} "
            f"| {len(hunks)} | {one_liner} |"
        )
    return "\n".join(lines) + "\n", unanchored


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", type=Path)
    parser.add_argument(
        "--queue",
        default=Path(".agentic-engineering/lessons/LESSONS.md"),
        type=Path,
    )
    parser.add_argument(
        "--out", default=Path(".agentic-engineering/lessons/INDEX.md"), type=Path
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if not args.queue.is_absolute():
        args.queue = args.root / args.queue
    if not args.out.is_absolute():
        args.out = args.root / args.out

    applied, malformed = parse_applied(args.queue)
    anchors = collect_anchors(args.root)
    index_text, unanchored = build_index(applied, anchors)
    for slug in unanchored:
        print(f"UNANCHORED: {slug} (applied, no anchors found)")
    for slug in malformed:
        print(f"MALFORMED: {slug} (second body line; first kept, fix the queue entry)")
    for slug in sorted(anchors):
        if slug in applied:
            continue
        # a digit-suffixed hunk (<base>-2) belongs to its base lesson, not a stray
        if slug[-1].isdigit() and slug.rsplit("-", 1)[0] in applied:
            continue
        print(f"STRAY: {slug} (anchor, no applied entry)")

    if args.check:
        if not args.out.exists():
            print(f"index absent: {args.out}")
            return 1
        return 0 if args.out.read_text() == index_text else 1
    args.out.write_text(index_text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
