/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'

const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/knowledge': typeof KnowledgeRoute
  '/people': typeof PeopleRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/knowledge': typeof KnowledgeRoute
  '/people': typeof PeopleRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/knowledge': typeof KnowledgeRoute
  '/people': typeof PeopleRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decisions' | '/knowledge' | '/people' | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decisions' | '/knowledge' | '/people' | '/tasks/$id'
  id: '__root__' | '/' | '/decisions' | '/knowledge' | '/people' | '/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PeopleRoute: typeof PeopleRoute
  TasksIdRoute: typeof TasksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRoute,
  KnowledgeRoute: KnowledgeRoute,
  PeopleRoute: PeopleRoute,
  TasksIdRoute: TasksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
