#!/usr/bin/env bash
# Rebuild docs/reference/catalog.md by scanning frontmatter of all knowledge notes.
# Installed to product repo at scripts/rebuild-catalog.sh by `facio-superpowers init`.
# Usage: scripts/rebuild-catalog.sh [--root <dir>] [--out <file>]

set -euo pipefail

ROOT="docs/reference"
OUT="$ROOT/catalog.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    --out)  OUT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

extract_field() {
  local file="$1" field="$2"
  awk -v f="$field" '
    /^---$/ { in_fm = !in_fm; next }
    in_fm && $0 ~ "^" f ":" { sub("^" f ":[[:space:]]*", ""); print; exit }
  ' "$file"
}

render_section() {
  local type_dir="$1"
  local found=0
  shopt -s nullglob
  for f in "$ROOT/$type_dir"/*.md; do
    [[ "$(basename "$f")" == "README.md" ]] && continue
    local id title maturity ref_count tags rel_path
    id=$(extract_field "$f" "id")
    title=$(extract_field "$f" "title")
    maturity=$(extract_field "$f" "maturity")
    ref_count=$(extract_field "$f" "ref_count")
    tags=$(extract_field "$f" "tags" | tr -d '[]')
    rel_path="./${type_dir}/$(basename "$f")"
    echo "- [${id}](${rel_path}) — ${title} · ${maturity} · ref_count: ${ref_count} · tags: ${tags}"
    found=1
  done
  shopt -u nullglob
  if [[ $found -eq 0 ]]; then
    echo "_(空 · M3 起累积)_"
  fi
}

cat > "$OUT" <<'HEADER'
<!-- AUTO-GENERATED by scripts/rebuild-catalog.sh; do not edit by hand -->
# Knowledge Catalog

> Single source of truth for `docs/reference/{decisions,guidelines,pitfalls}/` lookup.
> spec-author Step 0 从这里加载相关 notes（progressive disclosure 入口）。
>
> AI 永远读 catalog，**不扫目录**。

## Decisions

HEADER

render_section "decisions" >> "$OUT"

cat >> "$OUT" <<'MID1'

## Guidelines

MID1

render_section "guidelines" >> "$OUT"

cat >> "$OUT" <<'MID2'

## Pitfalls

MID2

render_section "pitfalls" >> "$OUT"

{
  echo ""
  echo "---"
  echo ""
  echo "**Last rebuild:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
} >> "$OUT"

echo "Rebuilt: $OUT"
