#!/usr/bin/env bash
# Render Antigravity's always-on rule from the canonical bootstrap and tool map.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${1:-$REPO_ROOT/rules/superpowers.md}"

{
  cat <<'HEADER'
---
trigger: always_on
description: Load Superpowers at the start of every Antigravity session
---

<!-- Generated by scripts/generate-antigravity-rule.sh. Do not edit directly. -->

The Superpowers bootstrap and Antigravity tool mapping are already loaded below.
Do not reopen those two files merely to load them. Read other skills when needed.

HEADER
  cat "$REPO_ROOT/skills/using-superpowers/SKILL.md"
  printf '\n\n'
  cat "$REPO_ROOT/skills/using-superpowers/references/antigravity-tools.md"
} > "$OUTPUT"
