#!/usr/bin/env bash
# Generates .github/copilot-instructions.md from source skill files.
# Run this after adding/modifying skills to keep the Copilot bootstrap in sync.
#
# Usage:
#   bash scripts/generate-copilot-instructions.sh              # default prefix ~/.copilot-superpowers
#   bash scripts/generate-copilot-instructions.sh --prefix .superpowers  # per-project install

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${REPO_ROOT}/.github/copilot-instructions.md"

SKILLS_DIR="${REPO_ROOT}/skills"
COPILOT_TOOLS="${SKILLS_DIR}/using-superpowers/references/copilot-tools.md"

# Default prefix for skill paths
PREFIX="~/.copilot-superpowers"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      PREFIX="$2"
      shift 2
      ;;
    --prefix=*)
      PREFIX="${1#*=}"
      shift
      ;;
    *)
      echo "Usage: $0 [--prefix <path>]" >&2
      exit 1
      ;;
  esac
done

# Strip trailing slash from prefix
PREFIX="${PREFIX%/}"

# Extract a frontmatter field value from a SKILL.md file
extract_field() {
  local file="$1"
  local field="$2"
  local in_frontmatter=false

  while IFS= read -r line; do
    if [ "$in_frontmatter" = false ] && [ "$line" = "---" ]; then
      in_frontmatter=true
      continue
    fi
    if [ "$in_frontmatter" = true ]; then
      if [ "$line" = "---" ]; then
        break
      fi
      # Match field: value (handles quoted and unquoted values)
      if [[ "$line" =~ ^${field}:\ *(.*) ]]; then
        local value="${BASH_REMATCH[1]}"
        # Strip surrounding quotes
        value="${value#\"}"
        value="${value%\"}"
        value="${value#\'}"
        value="${value%\'}"
        printf '%s' "$value"
        return
      fi
    fi
  done < "$file"
}

# Build the skills catalog by scanning all skills/*/SKILL.md
build_catalog() {
  local design_skills=()
  local testing_skills=()
  local debugging_skills=()
  local workflow_skills=()
  local meta_skills=()

  for skill_dir in "${SKILLS_DIR}"/*/; do
    local skill_file="${skill_dir}SKILL.md"
    [ -f "$skill_file" ] || continue

    local name
    name=$(extract_field "$skill_file" "name")
    [ -n "$name" ] || continue

    local desc
    desc=$(extract_field "$skill_file" "description")

    local dir_name
    dir_name=$(basename "$skill_dir")
    local skill_path="${PREFIX}/skills/${dir_name}/SKILL.md"
    local entry="- **${name}** (\`${skill_path}\`): ${desc}"

    # Categorize
    case "$name" in
      brainstorming|writing-plans|executing-plans)
        design_skills+=("$entry") ;;
      test-driven-development|verification-before-completion|requesting-code-review|receiving-code-review)
        testing_skills+=("$entry") ;;
      systematic-debugging)
        debugging_skills+=("$entry") ;;
      using-superpowers|writing-skills)
        meta_skills+=("$entry") ;;
      *)
        workflow_skills+=("$entry") ;;
    esac
  done

  printf '## Available Skills\n\n'
  printf 'Read the relevant SKILL.md file when any of these skills apply to your task.\n\n'

  printf '**Design & Planning**\n'
  for entry in "${design_skills[@]}"; do printf '%s\n' "$entry"; done
  printf '\n'

  printf '**Testing & Quality**\n'
  for entry in "${testing_skills[@]}"; do printf '%s\n' "$entry"; done
  printf '\n'

  printf '**Debugging**\n'
  for entry in "${debugging_skills[@]}"; do printf '%s\n' "$entry"; done
  printf '\n'

  printf '**Workflow**\n'
  for entry in "${workflow_skills[@]}"; do printf '%s\n' "$entry"; done
  printf '\n'

  printf '**Meta**\n'
  for entry in "${meta_skills[@]}"; do printf '%s\n' "$entry"; done
}

# --- Main ---

# Validate source files exist
if [ ! -f "$COPILOT_TOOLS" ]; then
  echo "ERROR: Required file not found: $COPILOT_TOOLS" >&2
  exit 1
fi

# Read source content
copilot_tools_content=$(cat "$COPILOT_TOOLS")
skills_catalog=$(build_catalog)

# Assemble the output — Copilot-native content (not raw using-superpowers dump)
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" << HEADER
<!-- AUTO-GENERATED by scripts/generate-copilot-instructions.sh — do not edit manually -->
<!-- Prefix: ${PREFIX} -->
<EXTREMELY_IMPORTANT>
You have superpowers — a skills-based development workflow.

## How to Use Skills

When a user's task matches a skill (see catalog below), read the skill file
and follow its instructions exactly.

To load a skill, read it: \`${PREFIX}/skills/<name>/SKILL.md\`

### Invoking Skills

Users may say things like:
- "Use the brainstorming skill"
- "Use TDD for this feature"
- "Debug this systematically"
- "Read ${PREFIX}/skills/brainstorming/SKILL.md and follow it"

When you recognize a skill applies, tell the user which skill you're using,
then read the SKILL.md file and follow it.

## Instruction Priority

Superpowers skills override default system prompt behavior, but **user instructions always take precedence**:

1. **User's explicit instructions** (CLAUDE.md, GEMINI.md, AGENTS.md, .github/copilot-instructions.md, direct requests) — highest priority
2. **Superpowers skills** — override default system behavior where they conflict
3. **Default system prompt** — lowest priority

If the user says "don't use TDD" and a skill says "always use TDD," follow the user's instructions.

## The Rule

**Read and follow relevant skills BEFORE any response or action.** Even a 1% chance a skill might apply means you should check the skill. If a skill turns out to be wrong for the situation, you don't need to use it.

\`\`\`dot
digraph skill_flow {
    "User message received" [shape=doublecircle];
    "Might any skill apply?" [shape=diamond];
    "Read the skill's SKILL.md file" [shape=box];
    "Announce: 'Using [skill] to [purpose]'" [shape=box];
    "Has checklist?" [shape=diamond];
    "Track progress with markdown checklist" [shape=box];
    "Follow skill exactly" [shape=box];
    "Respond (including clarifications)" [shape=doublecircle];

    "User message received" -> "Might any skill apply?";
    "Might any skill apply?" -> "Read the skill's SKILL.md file" [label="yes, even 1%"];
    "Might any skill apply?" -> "Respond (including clarifications)" [label="definitely not"];
    "Read the skill's SKILL.md file" -> "Announce: 'Using [skill] to [purpose]'";
    "Announce: 'Using [skill] to [purpose]'" -> "Has checklist?";
    "Has checklist?" -> "Track progress with markdown checklist" [label="yes"];
    "Has checklist?" -> "Follow skill exactly" [label="no"];
    "Track progress with markdown checklist" -> "Follow skill exactly";
}
\`\`\`

## Red Flags

These thoughts mean STOP — you're rationalizing:

| Thought | Reality |
|---------|---------|
| "This is just a simple question" | Questions are tasks. Check for skills. |
| "I need more context first" | Skill check comes BEFORE clarifying questions. |
| "Let me explore the codebase first" | Skills tell you HOW to explore. Check first. |
| "I can check git/files quickly" | Files lack conversation context. Check for skills. |
| "Let me gather information first" | Skills tell you HOW to gather information. |
| "This doesn't need a formal skill" | If a skill exists, use it. |
| "I remember this skill" | Skills evolve. Read current version. |
| "This doesn't count as a task" | Action = task. Check for skills. |
| "The skill is overkill" | Simple things become complex. Use it. |
| "I'll just do this one thing first" | Check BEFORE doing anything. |
| "This feels productive" | Undisciplined action wastes time. Skills prevent this. |
| "I know what that means" | Knowing the concept ≠ reading the skill. Read it. |

## Skill Priority

When multiple skills could apply, use this order:

1. **Process skills first** (brainstorming, debugging) — these determine HOW to approach the task
2. **Implementation skills second** (frontend-design, mcp-builder) — these guide execution

"Let's build X" → brainstorming first, then implementation skills.
"Fix this bug" → debugging first, then domain-specific skills.

## Skill Types

**Rigid** (TDD, debugging): Follow exactly. Don't adapt away discipline.

**Flexible** (patterns): Adapt principles to context.

The skill itself tells you which.

## Tool Mapping

HEADER

# Append tool mapping
printf '%s\n\n' "$copilot_tools_content" >> "$OUTPUT"

# Append skills catalog
printf '%s\n' "$skills_catalog" >> "$OUTPUT"

# Close the wrapper
printf '</EXTREMELY_IMPORTANT>\n' >> "$OUTPUT"

echo "Generated: $OUTPUT (prefix: $PREFIX)"
