#!/usr/bin/env bash
# Render Antigravity's always-on rule from the canonical bootstrap and tool map.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${1:-$REPO_ROOT/rules/superpowers.md}"
SKILL_SRC="$REPO_ROOT/skills/using-superpowers/SKILL.md"
MAP_SRC="$REPO_ROOT/skills/using-superpowers/references/antigravity-tools.md"

for src in "$SKILL_SRC" "$MAP_SRC"; do
  test -r "$src" || { echo "FAIL: bootstrap source is missing or unreadable: $src" >&2; exit 1; }
done

if [[ "$OUTPUT" == /dev/* ]]; then
  {
    cat <<'HEADER'
---
trigger: always_on
description: Load Superpowers at the start of every Antigravity session
---

<!-- Generated by scripts/generate-antigravity-rule.sh. Do not edit directly. -->

The Superpowers bootstrap and Antigravity tool mapping are already loaded below.
Do not reopen those two files merely to load them. Read other skills when needed.

HEADER
    cat "$SKILL_SRC"
    printf '\n\n'
    cat "$MAP_SRC"
  } > "$OUTPUT"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"
TMP_OUTPUT="$(mktemp "$(dirname "$OUTPUT")/.superpowers.XXXXXX")"
trap 'rm -f "$TMP_OUTPUT"' EXIT

{
  cat <<'HEADER'
---
trigger: always_on
description: Load Superpowers at the start of every Antigravity session
---

<!-- Generated by scripts/generate-antigravity-rule.sh. Do not edit directly. -->

The Superpowers bootstrap and Antigravity tool mapping are already loaded below.
Do not reopen those two files merely to load them. Read other skills when needed.

HEADER
  cat "$SKILL_SRC"
  printf '\n\n'
  cat "$MAP_SRC"
} > "$TMP_OUTPUT"

mv "$TMP_OUTPUT" "$OUTPUT"
trap - EXIT
