<#
.SYNOPSIS
    Create (or reset) the `gh-pages` orphan branch with just `.nojekyll`.

.DESCRIPTION
    The skill-eval workflow's publish job writes data files to a `gh-pages`
    branch. This is a one-shot helper that initializes the branch as an
    orphan with no history, containing only `.nojekyll` so GitHub Pages
    serves files without Jekyll processing.

    Working tree contents are preserved by default; pass `-Force` to
    reset the branch completely.

    Requires git ≥ 2.42 (uses `git worktree add --orphan`).

.PARAMETER RepoRoot
    Repo root. Defaults to current directory.

.PARAMETER Remote
    Remote to push to. Default `origin`.

.PARAMETER Force
    If set, delete and recreate the gh-pages branch (DESTRUCTIVE — drops
    all existing published data).

.PARAMETER NoPush
    If set, only create the branch locally; don't push to remote.

.EXAMPLE
    pwsh -File scripts/init-gh-pages.ps1
#>

[CmdletBinding()]
param(
    [string] $RepoRoot,
    [string] $Remote = 'origin',
    [switch] $Force,
    [switch] $NoPush
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path

Push-Location $RepoRoot
try {
    # Refuse to run with uncommitted changes — we'll be doing risky operations.
    $dirty = & git status --porcelain
    if ($LASTEXITCODE -ne 0) { throw "git status failed in $RepoRoot" }
    if ($dirty) {
        throw "Working tree has uncommitted changes. Commit or stash before running this script."
    }

    $current = & git rev-parse --abbrev-ref HEAD
    if ($LASTEXITCODE -ne 0) { throw "git rev-parse failed" }

    # Probe remote/local for existing gh-pages.
    & git fetch $Remote 'gh-pages' 2>$null
    $remoteHas = $LASTEXITCODE -eq 0
    $localExists = $false
    & git rev-parse --verify --quiet refs/heads/gh-pages *>$null
    if ($LASTEXITCODE -eq 0) { $localExists = $true }

    if (($remoteHas -or $localExists) -and -not $Force) {
        Write-Host "gh-pages already exists. Pass -Force to reset (destructive)." -ForegroundColor Yellow
        return
    }

    if ($Force) {
        if ($localExists) {
            Write-Host "Deleting local gh-pages..." -ForegroundColor Yellow
            & git branch -D gh-pages | Out-Null
        }
    }

    # Create orphan in a temp worktree to avoid disturbing this checkout.
    $tmpWorktree = Join-Path ([IO.Path]::GetTempPath()) ("ghpages-init-" + [Guid]::NewGuid().ToString('N').Substring(0,8))
    & git worktree add --orphan -b gh-pages $tmpWorktree
    if ($LASTEXITCODE -ne 0) { throw "git worktree add --orphan failed" }
    try {
        Push-Location $tmpWorktree
        try {
            # Wipe any tracked files inherited from index.
            & git rm -rf --quiet . 2>$null
            Set-Content -Path '.nojekyll' -Value '' -NoNewline -Encoding utf8
            Set-Content -Path 'README.md' -Value "# superpowers eval data`n`nGenerated by the skill-eval CI workflow. Do not edit by hand.`n" -Encoding utf8
            & git add .nojekyll README.md
            & git -c user.email=ci@example.invalid -c user.name=ci commit -m "Initialize gh-pages" | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "git commit failed" }
            if (-not $NoPush) {
                if ($Force -and $remoteHas) {
                    & git push --force-with-lease $Remote gh-pages
                } else {
                    & git push -u $Remote gh-pages
                }
                if ($LASTEXITCODE -ne 0) { throw "git push failed" }
            }
        } finally {
            Pop-Location
        }
    } finally {
        & git worktree remove --force $tmpWorktree 2>$null | Out-Null
    }

    Write-Host "gh-pages initialized." -ForegroundColor Green
} finally {
    Pop-Location
}
